version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:80"
      - "9000:443"
    depends_on:
      - db
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - password=Your_password123
  db:
    image: "mysql"
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: InventoryData
      MYSQL_ROOT_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  ui:
    build:
      context: ./
      dockerfile: ./UI.Dockerfile
      target: "localDev"
    ports:
      - "8080:8080"
    
    depends_on:
      - api
  
  #InventoryData:
  #    image: postgres:13.1
  #    healthcheck:
  #      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
  #      timeout: 45s
  #      interval: 10s
  #      retries: 10
  #    restart: always
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=password
  #      - APP_DB_USER=docker
  #      - APP_DB_PASS=docker
  #      - APP_DB_NAME=docker
  #    volumes:
  #      - ./db:/docker-entrypoint-initdb.d/
  #    ports:
  #      - 5432:5432
  #    depends_on:
  #        - db
  #db:
  #    image: "mysql"
  #    command: --init-file /data/application/init.sql
  #    volumes:
  #        - ./init.sql:/data/application/init.sql
  #    cap_add:
  #        - SYS_NICE  # CAP_SYS_NICE
  #    environment:
  #        MYSQL_ROOT_USER: root
  #        MYSQL_DATABASE: product_catalog
  #        MYSQL_ROOT_PASSWORD: "Your_password123"
  #        ACCEPT_EULA: "Y"
