
CREATE DATABASE IF NOT EXISTS  InventoryData;

USE InventoryData;


CREATE TABLE IF NOT EXISTS ItemList(
Brand VARCHAR(255),
GenericName VARCHAR(255),
Price DECIMAL(8,2),
Size VARCHAR(255),
ItemID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(ItemID),
FOREIGN KEY (Password)
    REFERENCES Login(Password)
);

CREATE TABLE IF NOT EXISTS PantryList(
PantryName VARCHAR(255),
PantryID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(PantryID),
FOREIGN KEY (Password)
    REFERENCES Login(Password)
);

CREATE TABLE IF NOT EXISTS PantryContents(
Quantity INT,
PCItemID INT,
PCPantryID INT,
PantryContentID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(PantryContentID),
FOREIGN KEY (PCItemID)
    REFERENCES ItemList(ItemID),
FOREIGN KEY (PCPantryID)
    REFERENCES PantryList(PantryID),
FOREIGN KEY (Password)
    REFERENCES Login(Password)
);

CREATE TABLE IF NOT EXISTS Login(
    UserName VARCHAR(225),
    Password INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (Password)
)